;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Thu Jun 3 2021
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

CODE    SEGMENT
        ASSUME CS:CODE, DS:DATA, ES:CODE, SS:CODE
	
	; ----------------- SETUP ----------------- ;
	ORG 0000H
	MOV AX, DATA
	MOV DS, AX
	MOV AL, 10000000B ; configure all ports as output in mode 0
	OUT PORT_CON, AL
	
	; ----------------- LOOP  ----------------- ;
	FOREVER:
	   
	    MOV AL, FONT[3]	; selected digit 0 of roll '003'
	    OUT PORTA, AL	; output data through portA
	    MOV AL, 00000001B	; selecting anode 0
	    OUT PORTB, AL
	    
	    MOV AL, FONT[0]	; selected digit 1 of roll '003'
	    OUT PORTA, AL	; output data through portA
	    MOV AL, 00000010B	; selecting anode 1
	    OUT PORTB, AL
	    
	    MOV AL, FONT[0]	; selected digit 2 of roll '003'
	    OUT PORTA, AL	; output data through portA
	    MOV AL, 00000100B	; selecting anode 2
	    OUT PORTB, AL
	    
	JMP FOREVER

CODE    ENDS

DATA 	SEGMENT
	
	PORTA EQU 00H
	PORTB EQU 02H
	PORTC EQU 04H
	PORT_CON EQU 06H
	
	; ----FONTS---- ;
	FONT  DB 11000000B	; 0
	      DB 11111001B	; 1
	      DB 10100100B	; 2
	      DB 10110000B	; 3
	      DB 10011001B	; 4
	      DB 10010010B	; 5
	      DB 10000010B	; 6
	      DB 11011000B	; 7
	      DB 10000000B	; 8
	      DB 10010000B	; 9
	      DB 10001000B	; A
	      DB 10000011B	; B
	      DB 11000110B	; C
	      DB 10100001B	; D
	      DB 10000110B	; E
	      DB 10001110B	; F
	      
DATA 	ENDS
        END 